[feat]: Updates on the landing page
Songaapp/songa.web pull request #23
Opened 2023-07-07 09:01 UTC by MarianaKomen

2023-07-13 04:55 UTC, mog-rn requested changes
Please have a look at the changes I have suggested and work on  them.

2023-07-13 04:55 UTC, mog-rn commented on app/globals.css
> -  background: #222222;
Do we really need this style here?

2023-07-13 04:55 UTC, mog-rn commented on app/layout.tsx
>  const inter = Inter({ subsets: ['latin'] })
You can remove this font.

2023-07-13 04:55 UTC, mog-rn commented on app/layout.tsx
>  import { useState } from 'react'
We are not using useState here so you can also remove this.

2023-07-13 04:55 UTC, mog-rn commented on app/layout.tsx
>  import { Inter } from 'next/font/google'
Remove this import too.

2023-07-13 04:55 UTC, mog-rn commented on app/page.tsx
> +      {/* <Services />
Remove these commented stuff.

2023-07-13 04:55 UTC, mog-rn commented on components/Elements/NavBar/index.tsx
> +const navLinks = [
In the NavBar folder create a links.ts file and move this json there. You can then eport it likeso:

`export const navLinks = [
    // ... rest of the json objects here
]`

2023-07-13 04:55 UTC, mog-rn commented on components/Elements/NavBar/index.tsx
> +        <div className=''>
Remove this empty className property

2023-07-13 04:55 UTC, mog-rn commented on components/Elements/NavBar/index.tsx
> +        <div className=''>
Remove empty className property

2023-07-13 04:55 UTC, mog-rn commented on components/Elements/NavBar/index.tsx
> +          {/* <div>
Remove this commented code.

2023-07-13 04:55 UTC, mog-rn commented on components/Elements/NavBar/index.tsx
> +                    {/* <button className='border-none my-4 xl:px-8 py-[8px] outline-none text-white rounded-md'>
Remove this commented code. We don't need login on this landing page

2023-07-13 04:55 UTC, mog-rn commented on components/Landing/Cards/index.tsx
> +                    {/* <Link href='/' className='text-red-500 text-center py-4 flex flex-row justify-center items-center gap-[0.5rem]'>
Remove this commented code in this file.

2023-07-13 04:55 UTC, mog-rn commented on components/Landing/Partnerships/index.tsx
> +                        alt=''
Add the alt text to the images.

2023-07-15 07:29 UTC, MarianaKomen commented on app/globals.css
> -  background: #222222;
No, we dont

2023-07-15 07:31 UTC, MarianaKomen commented on app/globals.css
> -  background: #222222;
Done

2023-07-15 07:31 UTC, MarianaKomen commented on app/layout.tsx
>  const inter = Inter({ subsets: ['latin'] })
Done

2023-07-15 07:31 UTC, MarianaKomen commented on app/layout.tsx
>  import { useState } from 'react'
Done

2023-07-15 07:31 UTC, MarianaKomen commented on app/layout.tsx
>  import { Inter } from 'next/font/google'
Done

2023-07-15 07:32 UTC, MarianaKomen commented on app/page.tsx
> +      {/* <Services />
Done

2023-07-15 07:34 UTC, MarianaKomen commented on components/Elements/NavBar/index.tsx
> +        <div className=''>
Done

2023-07-15 07:34 UTC, MarianaKomen commented on components/Elements/NavBar/index.tsx
> +          {/* <div>
Done

2023-07-15 07:34 UTC, MarianaKomen commented on components/Elements/NavBar/index.tsx
> +                    {/* <button className='border-none my-4 xl:px-8 py-[8px] outline-none text-white rounded-md'>
Done

2023-07-15 07:39 UTC, MarianaKomen commented on components/Landing/Cards/index.tsx
> +                    {/* <Link href='/' className='text-red-500 text-center py-4 flex flex-row justify-center items-center gap-[0.5rem]'>
Done

2023-07-15 07:45 UTC, MarianaKomen commented on components/Landing/Partnerships/index.tsx
> +                        alt=''
Done

2023-07-15 08:28 UTC, mog-rn reviewed
There are a few things you haven't finished working on.

2023-07-16 23:55 UTC, merged